version: "3"
services:
  jupyter:
    build:
      context: ./jupyter
    image: markusmo3/custom-jupyter
    ports:
     - "8888:8888"
    volumes:
     - "./notebooks:/notebooks"
     - "./data/work:/data"
     - "./src:/src:ro"
# doesnt work on windows sadly...
#  mongo:
#    image: mongo
#    restart: always
#    ports:
#      - "27017-27019:27017-27019"
#    environment:
#      - MONGO_INITDB_DATABASE=oth
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=root
#    volumes:
#     - "./mongodb:/data/db"
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - "8887:8081"
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=root