version: "3"
services:
  jupyter:
    build:
      context: ./jupyter
    image: markusmo3/custom-jupyter
    ports:
     - "8888:8888"
    volumes:
     - "./notebooks:/notebooks"
     - "./data/work:/data"
